language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-mirage.sh
script: bash -ex .travis-mirage.sh
sudo: required
dist: xenial
env:
  matrix:
  - OCAML_VERSION=4.08 MIRAGE_BACKEND=unix FLAGS="-vv --net socket"
  - OCAML_VERSION=4.08 MIRAGE_BACKEND=unix FLAGS="-vv --net direct"
  - OCAML_VERSION=4.08 MIRAGE_BACKEND=xen  XENIMG="openmirageorg"
    PINS="travis-senv:https://github.com/hannesm/travis-senv.git#fix fat-filesystem:https://github.com/samoht/ocaml-fat.git#revert-sector-size"
    FLAGS="-vv --net direct --dhcp false --ipv4 46.43.42.135/28
    --ipv4-gateway 46.43.42.129
    --host openmirage.org --redirect https://mirage.io"
  - OCAML_VERSION=4.08 MIRAGE_BACKEND=xen XENIMG="mirageio"
    PINS="travis-senv:https://github.com/hannesm/travis-senv.git#fix fat-filesystem:https://github.com/samoht/ocaml-fat.git#revert-sector-size"
    FLAGS="-vv --net direct --dhcp false --ipv4 46.43.42.136/28
    --ipv4-gateway 46.43.42.129 --tls true
    --secrets-kv_ro fat --host mirage.io"
  global:
  - SRC_DIR=./src
